# Generated by Django 3.2.19 on 2024-08-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20240826_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
